"""add is_admin column

Revision ID: efa1461c6678
Revises: 
Create Date: 2026-03-09 17:14:17.256039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'efa1461c6678'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_column('original_price')
        batch_op.drop_column('parent_company')
        batch_op.drop_column('student_price')
        batch_op.drop_column('benefits')
        batch_op.drop_column('discount')
        batch_op.drop_column('link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('discount', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('benefits', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('student_price', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('parent_company', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('original_price', mysql.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
